---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: zcash-build-bench
spec:    
  params:
    - name: JOBS
      default: "4"
      type: string
    - name: BUILD_FOR_HOST
      default: x86_64-pc-linux-gnu
      type: string
    - name: CONFIGURE_FLAGS
      default: ""
      type: string
    - name: BUILD_CONTAINER
      default: electriccoinco/zcashd-bench-debian10
      type: string
    - name: TEST_TARGET
      default: ""
      type: string
  resources:
    inputs:
      - name: source
        type: git
  steps:
    - name: build
      image: $(params.BUILD_CONTAINER)
      script: |
        #!/bin/bash
        set -o pipefail
        cd workspace/source
        echo $(git rev-parse HEAD)
        echo $(git rev-parse --short HEAD)
        
        if [ "$(params.BUILD_FOR_HOST)" == "x86_64-apple-darwin11" ]
        then
            mkdir -p depends/SDKs
            curl -fs https://ecc.mypinata.cloud/ipfs/QmeSwckvSCGL9SXGdEHoAyqXdzD7T9HYTwsC34Bj5EVDF5 \
              -o depends/SDKs/Xcode-11.3.1-11C505-extracted-SDK-with-libcxx-headers.tar.gz
            tar zxvf depends/SDKs/Xcode-11.3.1-11C505-extracted-SDK-with-libcxx-headers.tar.gz \
              -C depends/SDKs
        fi              

        CONFIGURE_FLAGS=$(params.CONFIGURE_FLAGS) HOST=$(params.BUILD_FOR_HOST) ./zcutil/build.sh -j$(params.JOBS)

    - name: bench-sleep
      image: $(params.BUILD_CONTAINER)
      script: |
        #!/bin/bash
        set -o pipefail
        python -m pip install pyblake2 pyflakes python-qpid-proton pyutil pyzmq requests simplejson
        
        cp -a /home/.zcash-params $HOME/
        cp -r /home/benchmark-200k-UTXOs.tar.xz /workspace/source
        cp -r /home/block-107134.tar.xz /workspace/source
        cd /workspace/source

        ./qa/zcash/performance-measurements.sh time sleep | jq  '[.[]|.runningtime | tonumber] | add / (. | length | tonumber)'

    - name: bench-createsaplingspend
      image: $(params.BUILD_CONTAINER)
      script: |
        #!/bin/bash
        set -o pipefail
        cp -a /home/.zcash-params $HOME/
        cp -r /home/benchmark-200k-UTXOs.tar.xz /workspace/source
        cp -r /home/block-107134.tar.xz /workspace/source
        cd /workspace/source

        ./qa/zcash/performance-measurements.sh time createsaplingspend | jq  '[.[]|.runningtime | tonumber] | add / (. | length | tonumber)'

    - name: bench-verifysaplingspend
      image: $(params.BUILD_CONTAINER)
      script: |
        #!/bin/bash
        set -o pipefail
        cp -a /home/.zcash-params $HOME/
        cp -r /home/benchmark-200k-UTXOs.tar.xz /workspace/source
        cp -r /home/block-107134.tar.xz /workspace/source
        cd /workspace/source

        ./qa/zcash/performance-measurements.sh time verifysaplingspend | jq  '[.[]|.runningtime | tonumber] | add / (. | length | tonumber)'

    - name: bench-createsaplingoutput
      image: $(params.BUILD_CONTAINER)
      script: |
        #!/bin/bash
        set -o pipefail
        cp -a /home/.zcash-params $HOME/
        cp -r /home/benchmark-200k-UTXOs.tar.xz /workspace/source
        cp -r /home/block-107134.tar.xz /workspace/source
        cd /workspace/source

        ./qa/zcash/performance-measurements.sh time createsaplingoutput | jq '[.[]|.runningtime | tonumber] | add / (. | length | tonumber)'

    - name: bench-verifysaplingoutput
      image: $(params.BUILD_CONTAINER)
      script: |
        #!/bin/bash
        set -o pipefail
        cp -a /home/.zcash-params $HOME/
        cp -r /home/benchmark-200k-UTXOs.tar.xz /workspace/source
        cp -r /home/block-107134.tar.xz /workspace/source
        cd /workspace/source

        ./qa/zcash/performance-measurements.sh time verifysaplingoutput | jq '[.[]|.runningtime | tonumber] | add / (. | length | tonumber)'

    - name: bench-createjoinsplit
      image: $(params.BUILD_CONTAINER)
      script: |
        #!/bin/bash
        set -o pipefail
        cp -a /home/.zcash-params $HOME/
        cp -r /home/benchmark-200k-UTXOs.tar.xz /workspace/source
        cp -r /home/block-107134.tar.xz /workspace/source
        cd /workspace/source

        ./qa/zcash/performance-measurements.sh time createjoinsplit | jq '[.[]|.runningtime | tonumber] | add / (. | length | tonumber)'

    - name: bench-verifyjoinsplit
      image: $(params.BUILD_CONTAINER)
      script: |
        #!/bin/bash
        set -o pipefail
        cp -a /home/.zcash-params $HOME/
        cp -r /home/benchmark-200k-UTXOs.tar.xz /workspace/source
        cp -r /home/block-107134.tar.xz /workspace/source
        cd /workspace/source

        ./qa/zcash/performance-measurements.sh time verifyjoinsplit | jq '[.[]|.runningtime | tonumber] | add / (. | length | tonumber)'

    - name: bench-verifyequihash
      image: $(params.BUILD_CONTAINER)
      script: |
        #!/bin/bash
        set -o pipefail
        cp -a /home/.zcash-params $HOME/
        cp -r /home/benchmark-200k-UTXOs.tar.xz /workspace/source
        cp -r /home/block-107134.tar.xz /workspace/source
        cd /workspace/source

        ./qa/zcash/performance-measurements.sh time verifyequihash | jq '[.[]|.runningtime | tonumber] | add / (. | length | tonumber)'

    - name: bench-connectblockslow
      image: $(params.BUILD_CONTAINER)
      script: |
        #!/bin/bash
        set -o pipefail
        cp -a /home/.zcash-params $HOME/
        cp -r /home/benchmark-200k-UTXOs.tar.xz /workspace/source
        cp -r /home/block-107134.tar.xz /workspace/source
        cd /workspace/source

        ./qa/zcash/performance-measurements.sh time connectblockslow | sed -n '2,$p' | jq '[.[]|.runningtime | tonumber] | add / (. | length | tonumber)'

    - name: bench-loadwallet-200k-recv
      image: $(params.BUILD_CONTAINER)
      script: |
        #!/bin/bash
        set -o pipefail
        cp -a /home/.zcash-params $HOME/
        cp -r /home/benchmark-200k-UTXOs.tar.xz /workspace/source
        cp -r /home/block-107134.tar.xz /workspace/source
        cd /workspace/source

        ./qa/zcash/performance-measurements.sh time loadwallet 200k-recv | sed 1d | jq '[.[]|.runningtime | tonumber] | add / (. | length | tonumber)'

    - name: bench-loadwallet-200k-send
      image: $(params.BUILD_CONTAINER)
      script: |
        #!/bin/bash
        set -o pipefail
        cp -a /home/.zcash-params $HOME/
        cp -r /home/benchmark-200k-UTXOs.tar.xz /workspace/source
        cp -r /home/block-107134.tar.xz /workspace/source
        cd /workspace/source

        ./qa/zcash/performance-measurements.sh time loadwallet 200k-send | sed 1d | jq '[.[]|.runningtime | tonumber] | add / (. | length | tonumber)'

    - name: bench-listunspent-200k-recv
      image: $(params.BUILD_CONTAINER)
      script: |
        #!/bin/bash
        set -o pipefail
        cp -a /home/.zcash-params $HOME/
        cp -r /home/benchmark-200k-UTXOs.tar.xz /workspace/source
        cp -r /home/block-107134.tar.xz /workspace/source
        cd /workspace/source

        ./qa/zcash/performance-measurements.sh time listunspent 200k-recv | sed 1d | jq '[.[]|.runningtime | tonumber] | add / (. | length | tonumber)'

    - name: bench-listunspent-200k-send
      image: $(params.BUILD_CONTAINER)
      script: |
        #!/bin/bash
        set -o pipefail
        cp -a /home/.zcash-params $HOME/
        cp -r /home/benchmark-200k-UTXOs.tar.xz /workspace/source
        cp -r /home/block-107134.tar.xz /workspace/source
        cd /workspace/source

        ./qa/zcash/performance-measurements.sh time listunspent 200k-send | sed 1d | jq '[.[]|.runningtime | tonumber] | add / (. | length | tonumber)'

